FROM node:18-alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /home/appuser

COPY package*.json ./

RUN npm install

COPY app.js ./

RUN chown -R appuser:appgroup /home/appuser

USER appuser

EXPOSE 8080

CMD [ "npm", "start" ]